version: "3.3"
services:
  server:
    build: ./server_python
    image: bal-ent-server
    environment:
      - BAL_ENT_SERVER_URL=http://localhost
      - BAL_ENT_SERVER_PORT=8000
      - BAL_ENT_API_KEY=some_key
      - BAL_ENT_MODEL=deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
    ports:
      - "8000:8000"
