version: "3.3"
services:
  server:
    build: ./server_python
    image: bal-ent-server
    environment:
      - BAL_ENT_SERVER_URL=http://localhost
      - BAL_ENT_SERVER_PORT=8000
    ports:
      - "8000:8000"
